<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->headTitle('EKDA - A Scottish Charity working in East Africa')->setSeparator(' - ')->setAutoEscape(false) ?>
        <meta name="format-detection" content="telephone=no">
        <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta charset="utf-8">

        <meta name="description" content="EKDA: El-Amin Kibera Development Association. A Scottish Charity working in East Africa">
        <meta name="keywords" content="East Africa, Scottish, Charity, Kibera, Development, Association">

        <meta property="og:type" content="website">
        <meta property="og:title" content="EKDA: Scottish Charity Working in East Africa">
        <meta property="og:url" content="http://www.ekda.org">
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico')); ?>
        
        <!-- Le scripts -->
        <?php echo $this->headScript(); ?>

        <!--[if lt IE 10]>
            <div style="background: #212121; padding: 10px 0; box-shadow: 3px 3px 5px 0 rgba(0,0,0,.3); clear: both; text-align:center; position: relative; z-index:1;">
                <a href="http://windows.microsoft.com/en-US/internet-explorer/">
                    <img src="/img/warning_bar_0000_us.jpg" border="0" height="42" width="820" 
                         alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today.">
                </a>
            </div>
            <script src="/vendor/html5shiv/dist/html5shiv.min.js"></script>
            <script src="/vendor/respond/dest/respond.min.js"></script>
        <![endif]-->

    </head>
    <body>
        <div class="container main-content-adjustments">
            <div class="row">
                <div class="col-md-6">
                    <a href="/"><img src="/img/logo.png" /></a>
                </div>
                <div id="nav-quick" class="col-md-6 for-lg-screen">
                    <ul>
                        <li><a href="/Index/donate"><span>Donate</span></a></li>
                        <li><a href="/Index/contacts"><span>Contact us</span></a></li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <div id="main-nav-lg">
                        <?php
                        $subMenuOptions = array(
                            'indent' => 16,
                            'minDepth' => 0,
                            'maxDepth' => 1,
                            'onlyActiveBranch' => true,
                            'renderParents' => false
                        );
                        echo $this->navigation('Navigation')->menu()->renderMenu(null, $subMenuOptions);
                        ?>                        
                    </div>

                    <div id="main-nav-sm" class="dropdown">
                        <a class="dropdown-toggle nav-text" type="button" data-toggle="dropdown" href="#">
                            <?php
                            $active = $this->navigation()->breadcrumbs()->findActive($this->navigation()->breadcrumbs()->getContainer(), 0, 1);
                            
                            if (isset($active['page'])) {
                                echo $active['page']->getLabel();
                            }
                            
                            ?>                      
                            <span class="caret"></span>
                        </a>

                        <?php
                        $subMenuOptions['ulClass'] = "dropdown-menu";
                        echo $this->navigation('Navigation')->menu()->renderMenu(null, $subMenuOptions);
                        ?>
                    </div>
                </div>

            </div>
            
            <div class="row">
                <div class="col-md-12 top10" id="EntryContentNode">
                    <div >
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            
        </div> <!-- /container -->
        
        
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    
                    <div class="nav-foot for-lg-screen">
                        <ul>
                            <li class="first"><span style="cursor: auto;">The El-Amin Kibera Development Association</span></li>
                            <li><span style="cursor: auto;">Chr. SC041294</span></li>
                            <li><span style="cursor: auto;">Cmp. SC372845</span></li>
                            <?php if ($this->environment == "development"):?> <li><span><a href="/wordpress/wp-login.php">WP</a></span></li><?php endif;?>
                            <li><span><a href="/admin/index">Admin</a></span></li>
                        </ul>

                        <div class="social-foot">
                            <a href="http://twitter.com/kdacharity" target="_blank"><img src="/img/twitter_icon.png" alt="Twitter" height="25" width="25"/></a>
                            <a href="http://www.youtube.com/kdacharity" target="_blank"><img src="/img/youtube_icon.gif" alt="YouTube" height="25" width="25"/></a>
                            <a href="https://picasaweb.google.com/kdacharity" target="_blank"><img src="/img/picasa_icon.jpg" alt="Picasa" height="25" width="25"/></a>
                        </div>
                    </div>
                    
                    <div class="nav-foot for-sm-screen">
                        <ul>
                            <li class="first"><span style="cursor: auto;">EKDA</span></li>
                            <li><span style="cursor: auto;">SC041294</span></li>
                            <li><span style="cursor: auto;">SC372845</span></li>
                        </ul>

                        <div class="social-foot">
                            <a href="http://twitter.com/kdacharity" target="_blank"><img src="/img/twitter_icon.png" alt="Twitter" height="25" width="25"/></a>
                            <a href="http://www.youtube.com/kdacharity" target="_blank"><img src="/img/youtube_icon.gif" alt="YouTube" height="25" width="25"/></a>
                            <a href="https://picasaweb.google.com/kdacharity" target="_blank"><img src="/img/picasa_icon.jpg" alt="Picasa" height="25" width="25"/></a>
                        </div>
                    </div>
                </div>
                
            </div>
        </div> <!-- /container -->
        
        
        <?php echo $this->partial("layout/messages", array('succ' => $this->succ, 'err' => $this->err, 'info' => $this->info)); ?>
        
        <script>
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', '<?php echo $this->analyticsTrackingID; ?>']);
            _gaq.push(['_trackPageview']);
            
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>        
        
    </body>
</html>
