<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('EKDA - A Scottish Charity working in East Africa')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap.min.css') 
                ->appendStylesheet($this->basePath() . '/vendor/bootstrap/dist/css/bootstrap-theme.min.css')
                ->appendStylesheet($this->basePath() . '/vendor/toastr/toastr.min.css')
                ->appendStylesheet($this->basePath() . '/vendor/ladda-bootstrap/dist/ladda-themeless.min.css')
                ->appendStylesheet($this->basePath() . '/vendor/font-awesome/css/font-awesome.min.css')
                ->appendStylesheet($this->basePath() . '/customcss/overrides.css')
                ->appendStylesheet($this->basePath() . '/customcss/style.css')
                ->appendStylesheet($this->basePath() . '/customcss/responsive.css')
                ->appendStylesheet($this->basePath() . '/customcss/custom.css')
        ; ?>

        <!-- Scripts -->
        <?php $headScript = $this->headScript()
                ->appendFile($this->basePath() . '/vendor/html5shiv/dist/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/vendor/respond/dest/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/vendor/jquery/dist/jquery.min.js')
                ->appendFile($this->basePath() . '/vendor/bootstrap/dist/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/vendor/knockout/dist/knockout.js')
                ->appendFile($this->basePath() . '/vendor/knockout.mapping/build/knockout.mapping.js')
                ->appendFile($this->basePath() . '/vendor/moment/min/moment.min.js')
                ->appendFile($this->basePath() . '/vendor/moment-timezone/builds/moment-timezone-with-data.min.js')
                ->appendFile($this->basePath() . '/vendor/toastr/toastr.min.js')
                ->appendFile($this->basePath() . '/vendor/ladda-bootstrap/dist/spin.min.js')
                ->appendFile($this->basePath() . '/vendor/ladda-bootstrap/dist/ladda.min.js')
                ->appendFile($this->basePath() . '/vendor/cookies.js/cookies.js')
                ->appendFile($this->basePath() . '/vendor/bootbox.js/bootbox.js')
                ->appendFile($this->basePath() . '/vendor/lodash/dist/lodash.min.js')
                ->appendFile($this->basePath() . '/customjs/namespace.js')
        ; ?>
        
        <!-- Models -->
        <?php 
            $directory  = new RecursiveDirectoryIterator('public/models');
            $flattened  = new RecursiveIteratorIterator($directory);
            $modelfiles = new RegexIterator($flattened, '/\.(?:js)$/');

            foreach($modelfiles as $filename => $file) {
                $headScript->appendFile(str_replace ("public", "", $filename));
            }
            
            echo $headScript;
        ?>

    </head>
    <body>
        <div class="container main-content-adjustments">
            <div class="row">
                <div class="col-md-6">
                    <a href="/"><img src="/img/logo.png" /></a>
                </div>
                <div id="nav-quick" class="col-md-6 for-lg-screen">
                    <ul>
                        <li><a href="/Index/donate"><span>Donate</span></a></li>
                        <li><a href="/Index/contacts"><span>Contact us</span></a></li>
                    </ul>
                </div>
                <div class="col-md-12">
                    <div id="main-nav-lg">
                        <?php
                        $subMenuOptions = array(
                            'indent' => 16,
                            'minDepth' => 0,
                            'maxDepth' => 1,
                            'onlyActiveBranch' => true,
                            'renderParents' => false
                        );
                        echo $this->navigation('Navigation')->menu()->renderMenu(null, $subMenuOptions);
                        ?>                        
                    </div>

                    <div id="main-nav-sm" class="dropdown">
                        <a class="dropdown-toggle nav-text" type="button" data-toggle="dropdown" href="#">
                            <?php
                            $active = $this->navigation()->breadcrumbs()->findActive($this->navigation()->breadcrumbs()->getContainer(), 0, 1);
                            
                            if (isset($active['page'])) {
                                echo $active['page']->getLabel();
                            }
                            
                            ?>                      
                            <span class="caret"></span>
                        </a>

                        <?php
                        $subMenuOptions['ulClass'] = "dropdown-menu";
                        echo $this->navigation('Navigation')->menu()->renderMenu(null, $subMenuOptions);
                        ?>
                    </div>
                </div>

            </div>
            
            <div class="row">
                <div class="col-md-12 top10" id="EntryContentNode">
                    <div >
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
            
        </div> <!-- /container -->
        
        
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    
                    <div class="nav-foot for-lg-screen">
                        <ul>
                            <li class="first"><span style="cursor: auto;">The El-Amin Kibera Development Association</span></li>
                            <li><span style="cursor: auto;">Chr. SC041294</span></li>
                            <li><span style="cursor: auto;">Cmp. SC372845</span></li>
                            <li><span><a href="/wordpress/wp-login.php">WP</a></span></li>
                            <li><span><a href="/admin/index">Admin</a></span></li>
                        </ul>

                        <div class="social-foot">
                            <a href="http://twitter.com/kdacharity" target="_blank"><img src="/img/twitter_icon.png" alt="Twitter" height="25" width="25"/></a>
                            <a href="http://www.youtube.com/kdacharity" target="_blank"><img src="/img/youtube_icon.gif" alt="YouTube" height="25" width="25"/></a>
                            <a href="https://picasaweb.google.com/kdacharity" target="_blank"><img src="/img/picasa_icon.jpg" alt="Picasa" height="25" width="25"/></a>
                        </div>
                    </div>
                    
                    <div class="nav-foot for-sm-screen">
                        <ul>
                            <li class="first"><span style="cursor: auto;">EKDA</span></li>
                            <li><span style="cursor: auto;">SC041294</span></li>
                            <li><span style="cursor: auto;">SC372845</span></li>
                        </ul>

                        <div class="social-foot">
                            <a href="http://twitter.com/kdacharity" target="_blank"><img src="/img/twitter_icon.png" alt="Twitter" height="25" width="25"/></a>
                            <a href="http://www.youtube.com/kdacharity" target="_blank"><img src="/img/youtube_icon.gif" alt="YouTube" height="25" width="25"/></a>
                            <a href="https://picasaweb.google.com/kdacharity" target="_blank"><img src="/img/picasa_icon.jpg" alt="Picasa" height="25" width="25"/></a>
                        </div>
                    </div>
                </div>
                
            </div>
        </div> <!-- /container -->
        
        
        <?php echo $this->inlineScript() ?>
        <?php echo $this->partial("layout/messages", array('succ' => $this->succ, 'err' => $this->err, 'info' => $this->info)); ?>
        
        <script>
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', '<?php echo $this->analyticsTrackingID; ?>']);
            _gaq.push(['_trackPageview']);
            
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>        
        
    </body>
</html>
