<!-- Modal -->
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Qurbani Donation</h4>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" data-bind="with: qurbani">
                <div class="form-group">
                    <label class="col-sm-3 control-label">Sheep</label>
                    <div class="col-sm-7">
                        <select class="form-control" data-bind="options: $parent.numbers, value: sheep"></select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Cows</label>
                    <div class="col-sm-7">
                        <select class="form-control" data-bind="options: $parent.numbers, value: cows"></select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Camels</label>
                    <div class="col-sm-7">
                        <select class="form-control" data-bind="options: $parent.numbers, value: camels"></select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Fullname</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" placeholder="Fullname" data-bind="value: fullname">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Email</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" placeholder="Email" data-bind="value: email">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Mobile</label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" placeholder="Mobile" data-bind="value: mobile">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Instructions</label>
                    <div class="col-sm-7">
                        <textarea type="text" class="form-control" rows="3" placeholder="Instructions" data-bind="value: instructions"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-7">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" data-bind="checked: isvoid"> Is Void
                            </label>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary ladda-button" data-style="zoom-out" data-bind="click: update">
                <span class="ladda-label">Save</span>
            </button>
        </div>
    </div>
</div>
