<script>
    $(function() {
        var dom = document.getElementById("EntryContentNode");
        var obj = new ekda.admin.QurbaniAdminModel();
        ko.applyBindings(obj, dom);
    });
</script>

<div data-bind="visible: qurbaniseason">
    <h2>Manual Donation</h2>
    <div data-bind="with: qurbani">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th class="col-md-6">Animal</th>
                    <th class="col-md-3">Quantity</th>
                    <th class="col-md-3 text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Sheep</td>
                    <td><select class="form-control" data-bind="options: $parent.numbers, value: sheep"></select></td>
                    <td class="text-right" data-bind="text: (sheep() * sheepCost())"></td>
                </tr>
                <tr>
                    <td>Cows</td>
                    <td><select class="form-control" data-bind="options: $parent.numbers, value: cows"></select></td>
                    <td class="text-right" data-bind="text: (cows() * cowCost())"></td>
                </tr>
                <tr>
                    <td>Camels</td>
                    <td><select class="form-control" data-bind="options: $parent.numbers, value: camels"></select></td>
                    <td class="text-right" data-bind="text: (camels() * camelCost())"></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td class="text-right"><h2 data-bind="text: '£ '+total()"></h2></td>
                </tr>
                <tr>
                    <td colspan="2">
                    </td>
                    <td class="text-right">
                        <button class="btn btn-primary btn-sm ladda-button" 
                                data-style="zoom-out"
                                data-bind="click: $parent.donate">
                            <span class="ladda-label">Donate</span>
                        </button>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>

    <hr/>

    <h2>Current Donors</h2>
    
    <button id="qurbani-search" class="btn btn-success btn-sm ladda-button" 
            data-style="zoom-out"
            data-bind="click: searchQurbani">
        <span class="ladda-label">Search</span>
    </button>
    &nbsp;
    <label>
        <input type="checkbox" data-bind="checked: purchasedonly"> Purchased Only
    </label>
    &nbsp;
    <label>
        <input type="checkbox" data-bind="checked: includevoid"> Include Void
    </label>
    
    <hr/>
    
    <table class="table table-condensed table-striped" style="font-size: small">
        <thead>
            <tr>
                <th class="col-md-1"></th>
                <th class="col-md-1">Sheep</th>
                <th class="col-md-1">Cows</th>
                <th class="col-md-1">Camels</th>
                <th class="col-md-6">Instructions</th>
                <th class="col-md-1">ID</th>
                <th class="col-md-1">Date</th>
                <th class="col-md-1">Actions</th>
            </tr>
        </thead>

        <tbody data-bind="if: (results().length == 0)">
            <tr>
                <td colspan="8"><em>No Donors</em></td>
            </tr>
        </tbody>

        <tbody data-bind="foreach: results">
            <tr>
                <td></td>
                <td data-bind="text: sheep"></td>
                <td data-bind="text: cows"></td>
                <td data-bind="text: camels"></td>
                <td>
                    <span class="break-word newline-text" data-bind="html: instructions"></span>
                </td>
                <td data-bind="text: donationid"></td>
                <td data-bind="text: moment(createddate).format('DD/MM')"></td>
                <td>
                    <span class="fa fa-pencil pointer-cursor"
                          data-toggle="modal" data-target="#qurbaniModal"
                          data-bind="click: $parent.editDonation">
                    </span>
                    &nbsp;
                    <strong class="pointer-cursor" style="color: red" title="Toggle Void" data-bind="click: $parent.toggleVoid, visible: isvoid">V</strong>
                    <strong class="pointer-cursor" style="color: green" title="Toggle Void" data-bind="click: $parent.toggleVoid, visible: !isvoid">A</strong>
                    &nbsp;
                    <span class="fa fa-envelope-o pointer-cursor"
                          data-bind="click: $parent.sendQurbaniCompleteAlert, visible: !iscomplete">
                    </span>
                </td>
            </tr>
        </tbody>

        <tbody style="background: #efe;" data-bind="visible: purchasedonly() && !includevoid()">
            <tr>
                <th>Purchased:</th>
                <th data-bind="text: purchasedSheep"></th>
                <th data-bind="text: purchasedCows"></th>
                <th data-bind="text: purchasedCamels"></th>
                <td colspan="4"></td>
            </tr>
            <tr>
                <th>Remaining:</th>
                <th data-bind="text: totalsheep()-purchasedSheep()"></th>
                <th data-bind="text: totalcows()-purchasedCows()"></th>
                <th data-bind="text: totalcamels()-purchasedCamels()"></th>
                <td colspan="4"></td>
            </tr>
            <tr>
                <th>Total:</th>
                <th data-bind="text: totalsheep"></th>
                <th data-bind="text: totalcows"></th>
                <th data-bind="text: totalcamels"></th>
                <td colspan="4"></td>
            </tr>
        </tbody>
    </table>
</div>

<div class="modal fade" id="qurbaniModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-bind="with: qurbaniViewModel">
    <?php echo $this->partial("admin/_qurbani_modal"); ?>
</div>