<script>
    $(function() {
        var inputData = ko.toJS(<?php echo $this->model; ?>);
        var dom = document.getElementById("EntryContentNode");
        var obj = new ekda.admin.QurbaniAdminModel(inputData);
        ko.applyBindings(obj, dom);
    });
</script>

<div data-bind="visible: qurbani.qurbaniseason">
    <h2>Manual Donation</h2>
    <div data-bind="with: qurbani">
        <table class="table table-condensed">
            <thead>
                <tr>
                    <th class="col-md-6">Animal</th>
                    <th class="col-md-3">Quantity</th>
                    <th class="col-md-3 text-right">Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Sheep</td>
                    <td><select class="form-control" data-bind="options: numbers, value: sheep"></select></td>
                    <td class="text-right" data-bind="text: (sheep() * sheepCost)"></td>
                </tr>
                <tr>
                    <td>Cows</td>
                    <td><select class="form-control" data-bind="options: numbers, value: cows"></select></td>
                    <td class="text-right" data-bind="text: (cows() * cowCost)"></td>
                </tr>
                <tr>
                    <td>Camels</td>
                    <td><select class="form-control" data-bind="options: numbers, value: camels"></select></td>
                    <td class="text-right" data-bind="text: (camels() * camelCost)"></td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td class="text-right"><h2 data-bind="text: '£ '+total()"></h2></td>
                </tr>
                <tr>
                    <td colspan="2">
                    </td>
                    <td class="text-right">
                        <button class="btn btn-primary btn-sm ladda-button" 
                                data-style="zoom-out"
                                data-bind="disable: addInstructions, click: donate">
                            <span class="ladda-label">Donate</span>
                        </button>
                    </td>
                </tr>

            </tbody>
        </table>
    </div>

    <hr/>

    <h2>Current Donors</h2>
    
    <table class="table table-condensed" style="font-size: small">
        <thead>
            <tr>
                <th class="col-md-1">Sheep</th>
                <th class="col-md-1">Cows</th>
                <th class="col-md-1">Camels</th>
                <th class="col-md-6">Instructions</th>
                <th class="col-md-1">ID</th>
                <th class="col-md-1">Date</th>
                <th class="col-md-1">Actions</th>
            </tr>
        </thead>

        <tbody data-bind="if: (results().length == 0)">
            <tr>
                <td colspan="7"><em>No Donors</em></td>
            </tr>
        </tbody>

        <tbody data-bind="foreach: results">
            <tr>
                <td data-bind="text: sheep"></td>
                <td data-bind="text: cows"></td>
                <td data-bind="text: camels"></td>
                <td>
                    <span class="break-word newline-text" data-bind="html: instructions"></span>
                </td>
                <td data-bind="text: donationid"></td>
                <td data-bind="text: moment(createddate).format('DD/MM')"></td>
                <td>
                    <span class="fa fa-pencil pointer-cursor"></span>
                    &nbsp;
                    <span class="fa fa-ban pointer-cursor"></span>
                </td>
            </tr>
        </tbody>

        <tbody style="background: #efe;">
            <tr>
                <th data-bind="text: purchasedSheep"></th>
                <th data-bind="text: purchasedCows"></th>
                <th data-bind="text: purchasedCamels"></th>
                <td colspan="4"></td>
            </tr>
            <tr>
                <th data-bind="text: details.totalsheep"></th>
                <th data-bind="text: details.totalcows"></th>
                <th data-bind="text: details.totalcamels"></th>
                <td colspan="4"></td>
            </tr>
        </tbody>
    </table>
</div>
