<!-- FOOTER -->
<table class="footer-wrap" style="border-top: 1px solid #999;">
    <tr>
        <td></td>
        <td class="container">
            
                <!-- content -->
                <div class="content">
                <table>
                <tr>
                    <td align="center">
                        <p>Thank you for donating to <a href="https://ekda.org" style="color:#111111;">EKDA</a>!</p>
                        <a href="https://ekda.org" title="EKDA"><img src="<?=$domainPath?>/img/logo.png" alt=""/></a>
                        <br/><br/>
                        <p><strong><a href="https://ekda.org" style="color:#111111;">www.ekda.org</a></strong></p>
                        <p><small>&copy; EKDA, Scottish Charity # SC041294</small></p>
                    </td>
                </tr>
            </table>
                </div><!-- /content -->
                
        </td>
        <td></td>
    </tr>
</table><!-- /FOOTER -->

</body>
</html>