<table class="order-table">
    <thead>
        <tr style="border-bottom: 1px solid #aaa;">
            <th style="width: 80%">Animals</th>
            <th style="width: 20%">Cost</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Sheep &times; <?=$noOfSheep?></td>
            <td><?=number_format($costOfSheep, 2, '.', '')?></td>
        </tr>
        <tr>
            <td>Cows &times; <?=$noOfCows?></td>
            <td><?=number_format($costOfCows, 2, '.', '')?></td>
        </tr>
        <tr>
            <td>Camels &times; <?=$noOfCamels?></td>
            <td><?=number_format($costOfCamels, 2, '.', '')?></td>
        </tr>
    </tbody>

    <tfoot>
        <tr>
            <td><strong>Total</strong></td>
            <td><strong>&pound;<?=number_format($total, 2, '.', '')?></strong></td>
        </tr>
    </tfoot>
</table>

<?php if ($instructions != null) :?>
    <h4 class="section-header">Instructions</h4>
    <p>The following were the instructions included:</p>
    <p><?=nl2br($instructions)?></p>
<?php endif; ?>

