<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Salam Aleikum (Peace be upon you)</h4>
                        <p>
                            Thank you for your Qurbani donation. This email is to confirm that your donation has been received successfully. 
                            We will send you a Confirmation once the Sacrifice has been performed.
                        </p>

                        <h4 class="section-header">Donation Details</h4>
                        <?php include("data/templates/items.phtml"); ?>
                        
                        <h4 class="section-header">Instructions</h4>
                        <p>The following were the instructions included:</p>
                        <p><?=nl2br($instructions)?></p>
                        
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
