<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Asalam Aleikum (Peace be upon you)</h4>
                        <p>
                            We thought you would like to know that your Qurbani has been performed.
                        </p>
                        
                        <?php if ($instructions != null && strlen(trim($instructions)) > 0) :?>
                            <h4 class="section-header">Your instructions to us</h4>
                            <p><?=nl2br($instructions)?></p>
                        <?php endif; ?>

                        <h4 class="section-header">Donation Details</h4>
                        <?php include("data/templates/items.phtml"); ?>
                        
                        <br/>
                        
                        <p>
                            We would like to take this opportunity to thank you for your donation. 
                            May Allah bless you for this deed. Amin.
                        </p>
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
