<?php include("data/templates/header.phtml"); ?>

<!-- BODY -->
<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" bgcolor="#FFFFFF">

            <div class="content">
            <table>
                <tr>
                    <td>
                        <h4>Asalam Aleikum (Peace be upon you)</h4>
                        <p>
                            Thank you for your Qurbani donation. This email is to confirm that your donation has been received successfully. 
                        </p>

                        <?php if ($instructions != null && strlen(trim($instructions)) > 0) :?>
                            <h6 class="section-header">Your instructions to us</h6>
                            <p><?=nl2br($instructions)?></p>
                        <?php endif; ?>

                        <h4 class="section-header">Donation Details</h4>
                        <?php include("data/templates/items.phtml"); ?>
                            
                        <br/>
                        
                        <p>
                            We will send you a Confirmation email once the Sacrifice has been completed.
                            Once again we would like to thank you for your donation.
                        </p>
                        
                        <br/>
                    </td>
                </tr>
            </table>
            </div>
                                    
        </td>
        <td></td>
    </tr>
</table>
<!-- /BODY -->

<?php include("data/templates/footer.phtml"); ?>
