<script>
    $(function() {
        var inputData = ko.toJS(<?php echo $this->model; ?>);
        var dom = document.getElementById("EntryContentNode");
        var obj = new ekda.index.PostsModel(inputData);
        ko.applyBindings(obj, dom);
    });
</script>

<h2>Donation Details</h2>
<p>The realisation of our ideas and projects depend greatly on donations and we are 
infinitely grateful to all our donors. Contributions can be made through the following modes.
<p>
<hr/>
<div data-bind="foreach: posts">
    <div class="post-item">
        <h3 data-bind="html: title"></h3>
        <div data-bind="html: content"></div>
    </div>    
</div>        
