<script>
    $(function() {
        var inputData = ko.toJS(<?php echo $this->model; ?>);
        var dom = document.getElementById("EntryContentNode");
        var obj = new ekda.index.NewsModel(inputData);
        ko.applyBindings(obj, dom);
    });
</script>

<div class="row">
    <div class="col-md-2">
        <div class="side-bar news-sidebar">
            <h3 class="pointer-cursor" data-bind="click: selectAllMonths">Months</h3>
            <ul class="navigation" data-bind="foreach: sidebar">
                <li data-bind="click: $parent.selectMonth">
                    <a href="#" data-bind="css: {'active' : active }, text: moment(month).format('YYYY MMMM')"></a>
                </li>
            </ul> 
        </div>
        
    </div>
    <div class="col-md-10">
        <h2 class="pointer-cursor" data-bind="click: selectAllMonths">Lastest News</h2>
        <hr/>
        <div data-bind="foreach: currentNews">
            <div class="post-item news-item">
                <h3 data-bind="html: title"></h3>
                <div data-bind="html: content"></div>
                <p class="post-date" data-bind="text: 'Posted on ' + moment.utc(date).format('MMMM Do, YYYY. hh:mma')"></p>
            </div>
        </div>        
    </div>
    
</div>

