<script>
    $(function() {
        var inputData = ko.toJS(<?php echo $this->model; ?>);
        var dom = document.getElementById("EntryContentNode");
        var obj = new ekda.index.PostsModel(inputData);
        ko.applyBindings(obj, dom);
    });
</script>

<h2>Sponsors</h2>
<p>We are infinitely grateful to all those who have helped and continued to help us realise our ideas. 
The following is a moderate list of some of the organisations, behind which are some very special 
people that have been greatly instrumental to us in our campaigns. May they be rewarded greatly for 
their selfless acts of kindness.</p>
<hr/>
<div data-bind="foreach: posts">
    <div class="post-item">
        <div data-bind="html: content"></div>
    </div>    
</div>        
